### ISSUE TITLE
No indication of Python Version

### ISSUE THREAD

**Issue by rawrgulmuffins** [lolobosse/InstrumentationServer#1]
Attempting to set up your application to see if I can answer your SO question and I'm having to guess based on the imports what version of Python is used.

**Comment by lolobosse** [comment]
Oh of course! I use 2.7.5

**Comment by lolobosse** [comment]
Hey,

I created a clear README.md to explain all the stuff (9884cbf765d3707b4ba2b42b252ab4753b835914)
